package com.kolown.camera.filter

enum class  FilterNames {
    FILTER_ORIGINAL ,
    FILTER_BLACK_WHITE_DEFAULT ,
    FILTER_BLACK_WHITE_BRIGHT ,
    FILTER_BLACK_WHITE_DARK,
    FILTER_BLUE_ORANGE,
    FILTER_EDGE_DETECTION,
    FILTER_PIXELIZE,
    FILTER_EM_INTERFERENCE,
    FILTER_TRIANGLES_MOSAIC,
    FILTER_LEGOFIED,
    FILTER_TILE_MOSAIC,
    FILTER_CHROMATIC_ABERRATION,
    FILTER_BASIC_DEFORM,
    FILTER_CONTRAST,
    FILTER_NOISE_WARP,
    FILTER_REFRACTION,
    FILTER_MAPPING,
    FILTER_CROSSHATCH,
    FILTER_LICHTENSTEIN_ESQUE,
    FILTER_ASCII_ART,
    FILTER_MONEY_FILTER,
    FILTER_CRACKED,
    FILTER_POLYGONIZATION,
    FILTER_JFA_VORONOI,




}
